version: '3.8'

services:
  ftp-server:
    image: fauria/vsftpd
    container_name: ftp-server
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - /ścieżka/do/lokalnego/katalogu:/home/vsftpd/user
    environment:
      - FTP_USER=user
      - FTP_PASS=password
    restart: always

  cyno_db:
    container_name: cyno_db
    restart: always
    platform: linux/x86_64
    build: ./database/cyno_db
    volumes:
      - ./database/cyno_db/scripts:/docker-entrypoint-initdb.d
      - ./database/cyno_db/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    env_file:
      - ./database/cyno_db/local.env
    # pseudo terminal
    tty: true

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8077:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=users_db,listings_db

  backend_app:
    build: ./backend/API_gateway
    ports:
      - "8000:8000"

