version: '3'
services:
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8077:80'
    environment:
      - PMA_HOST=db
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '5506:3306'
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin